global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "rabbitmq-exporter"
    static_configs:
      - targets: ["rabbitmq-exporter:9419"]

  - job_name: "workoutservice"
    metrics_path: /metrics
    static_configs:
      - targets: ["workoutservice:8080"]