version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: fitlog-postgres
    environment:
      POSTGRES_DB: fitlog
      POSTGRES_USER: fitlog
      POSTGRES_PASSWORD: fitlog_pw
    ports:
      - "5432:5432"
    volumes:
      - fitlog_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fitlog -d fitlog"]
      interval: 5s
      timeout: 5s
      retries: 10

  rabbitmq:
    image: rabbitmq:3-management
    container_name: fitlog-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics -q ping"]
      interval: 10s
      timeout: 5s
      retries: 10

  workoutservice:
    build:
      context: .
      dockerfile: WorkoutService/Dockerfile
    container_name: fitlog-workoutservice
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "http://+:8080"
      ConnectionStrings__WorkoutDb: "Host=postgres;Port=5432;Database=fitlog;Username=fitlog;Password=fitlog_pw"
      RabbitMq__Host: "rabbitmq"
    ports:
      - "5001:8080"
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  rabbitmq-exporter:
    image: kbudde/rabbitmq-exporter:latest
    container_name: fitlog-rabbitmq-exporter
    environment:
      RABBIT_URL: "http://rabbitmq:15672"
      RABBIT_USER: "guest"
      RABBIT_PASSWORD: "guest"
      PUBLISH_PORT: "9419"
    ports:
      - "9419:9419"
    depends_on:
      rabbitmq:
        condition: service_healthy

  prometheus:
    image: prom/prometheus:latest
    container_name: fitlog-prometheus
    volumes:
      - ./observability/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    depends_on:
      - rabbitmq-exporter

  grafana:
    image: grafana/grafana:latest
    container_name: fitlog-grafana
    environment:
      GF_SECURITY_ADMIN_USER: "admin"
      GF_SECURITY_ADMIN_PASSWORD: "admin"
    ports:
      - "3000:3000"
    volumes:
      - ./observability/grafana/provisioning:/etc/grafana/provisioning:ro
    depends_on:
      - prometheus

volumes:
  fitlog_postgres_data:
  mongo_data:

